"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var $ = require("jquery");
var UniVe;
(function (UniVe) {
    var TAW;
    (function (TAW) {
        var Framework;
        (function (Framework) {
            var Auth;
            (function (Auth) {
                var AuthService = /** @class */ (function () {
                    function AuthService(fullServerEndpoint) {
                        this.FullServerEndpoint = fullServerEndpoint;
                    }
                    AuthService.prototype.Signup = function (signupRequest, successCallback) {
                        $.post(this.FullServerEndpoint, JSON.stringify(signupRequest), successCallback);
                    };
                    return AuthService;
                }());
                Auth.AuthService = AuthService;
                var Country;
                (function (Country) {
                    Country[Country["Afghanistan"] = 0] = "Afghanistan";
                    Country[Country["Albania"] = 1] = "Albania";
                    Country[Country["Algeria"] = 2] = "Algeria";
                    Country[Country["Andorra"] = 3] = "Andorra";
                    Country[Country["Angola"] = 4] = "Angola";
                    Country[Country["Antigua_Barbuda"] = 5] = "Antigua_Barbuda";
                    Country[Country["Argentina"] = 6] = "Argentina";
                    Country[Country["Armenia"] = 7] = "Armenia";
                    Country[Country["Australia"] = 8] = "Australia";
                    Country[Country["Austria"] = 9] = "Austria";
                    Country[Country["Azerbaijan"] = 10] = "Azerbaijan";
                    Country[Country["Bahamas"] = 11] = "Bahamas";
                    Country[Country["Bahrain"] = 12] = "Bahrain";
                    Country[Country["Bangladesh"] = 13] = "Bangladesh";
                    Country[Country["Barbados"] = 14] = "Barbados";
                    Country[Country["Belarus"] = 15] = "Belarus";
                    Country[Country["Belgium"] = 16] = "Belgium";
                    Country[Country["Belize"] = 17] = "Belize";
                    Country[Country["Benin"] = 18] = "Benin";
                    Country[Country["Bhutan"] = 19] = "Bhutan";
                    Country[Country["Bolivia"] = 20] = "Bolivia";
                    Country[Country["Bosnia_Herzegovina"] = 21] = "Bosnia_Herzegovina";
                    Country[Country["Botswana"] = 22] = "Botswana";
                    Country[Country["Brazil"] = 23] = "Brazil";
                    Country[Country["Brunei"] = 24] = "Brunei";
                    Country[Country["Bulgaria"] = 25] = "Bulgaria";
                    Country[Country["BurkinaFaso"] = 26] = "BurkinaFaso";
                    Country[Country["Burundi"] = 27] = "Burundi";
                    Country[Country["CaboVerde"] = 28] = "CaboVerde";
                    Country[Country["Cambodia"] = 29] = "Cambodia";
                    Country[Country["Cameroon"] = 30] = "Cameroon";
                    Country[Country["Canada"] = 31] = "Canada";
                    Country[Country["CentralAfricanRepublic"] = 32] = "CentralAfricanRepublic";
                    Country[Country["Chad"] = 33] = "Chad";
                    Country[Country["Chile"] = 34] = "Chile";
                    Country[Country["China"] = 35] = "China";
                    Country[Country["Colombia"] = 36] = "Colombia";
                    Country[Country["Comoros"] = 37] = "Comoros";
                    Country[Country["DemocraticRepublicoftheCongo"] = 38] = "DemocraticRepublicoftheCongo";
                    Country[Country["RepublicoftheCongo"] = 39] = "RepublicoftheCongo";
                    Country[Country["CostaRica"] = 40] = "CostaRica";
                    Country[Country["CotedIvoire"] = 41] = "CotedIvoire";
                    Country[Country["Croatia"] = 42] = "Croatia";
                    Country[Country["Cuba"] = 43] = "Cuba";
                    Country[Country["Cyprus"] = 44] = "Cyprus";
                    Country[Country["CzechRepublic"] = 45] = "CzechRepublic";
                    Country[Country["Denmark"] = 46] = "Denmark";
                    Country[Country["Djibouti"] = 47] = "Djibouti";
                    Country[Country["Dominica"] = 48] = "Dominica";
                    Country[Country["DominicanRepublic"] = 49] = "DominicanRepublic";
                    Country[Country["Ecuador"] = 50] = "Ecuador";
                    Country[Country["Egypt"] = 51] = "Egypt";
                    Country[Country["ElSalvador"] = 52] = "ElSalvador";
                    Country[Country["EquatorialGuinea"] = 53] = "EquatorialGuinea";
                    Country[Country["Eritrea"] = 54] = "Eritrea";
                    Country[Country["Estonia"] = 55] = "Estonia";
                    Country[Country["Ethiopia"] = 56] = "Ethiopia";
                    Country[Country["Fiji"] = 57] = "Fiji";
                    Country[Country["Finland"] = 58] = "Finland";
                    Country[Country["France"] = 59] = "France";
                    Country[Country["Gabon"] = 60] = "Gabon";
                    Country[Country["Gambia"] = 61] = "Gambia";
                    Country[Country["Georgia"] = 62] = "Georgia";
                    Country[Country["Germany"] = 63] = "Germany";
                    Country[Country["Ghana"] = 64] = "Ghana";
                    Country[Country["Greece"] = 65] = "Greece";
                    Country[Country["Grenada"] = 66] = "Grenada";
                    Country[Country["Guatemala"] = 67] = "Guatemala";
                    Country[Country["Guinea"] = 68] = "Guinea";
                    Country[Country["Guinea_Bissau"] = 69] = "Guinea_Bissau";
                    Country[Country["Guyana"] = 70] = "Guyana";
                    Country[Country["Haiti"] = 71] = "Haiti";
                    Country[Country["Honduras"] = 72] = "Honduras";
                    Country[Country["Hungary"] = 73] = "Hungary";
                    Country[Country["Iceland"] = 74] = "Iceland";
                    Country[Country["India"] = 75] = "India";
                    Country[Country["Indonesia"] = 76] = "Indonesia";
                    Country[Country["Iran"] = 77] = "Iran";
                    Country[Country["Iraq"] = 78] = "Iraq";
                    Country[Country["Ireland"] = 79] = "Ireland";
                    Country[Country["Israel"] = 80] = "Israel";
                    Country[Country["Italy"] = 81] = "Italy";
                    Country[Country["Jamaica"] = 82] = "Jamaica";
                    Country[Country["Japan"] = 83] = "Japan";
                    Country[Country["Jordan"] = 84] = "Jordan";
                    Country[Country["Kazakhstan"] = 85] = "Kazakhstan";
                    Country[Country["Kenya"] = 86] = "Kenya";
                    Country[Country["Kiribati"] = 87] = "Kiribati";
                    Country[Country["Kosovo"] = 88] = "Kosovo";
                    Country[Country["Kuwait"] = 89] = "Kuwait";
                    Country[Country["Kyrgyzstan"] = 90] = "Kyrgyzstan";
                    Country[Country["Laos"] = 91] = "Laos";
                    Country[Country["Latvia"] = 92] = "Latvia";
                    Country[Country["Lebanon"] = 93] = "Lebanon";
                    Country[Country["Lesotho"] = 94] = "Lesotho";
                    Country[Country["Liberia"] = 95] = "Liberia";
                    Country[Country["Libya"] = 96] = "Libya";
                    Country[Country["Liechtenstein"] = 97] = "Liechtenstein";
                    Country[Country["Lithuania"] = 98] = "Lithuania";
                    Country[Country["Luxembourg"] = 99] = "Luxembourg";
                    Country[Country["Macedonia"] = 100] = "Macedonia";
                    Country[Country["Madagascar"] = 101] = "Madagascar";
                    Country[Country["Malawi"] = 102] = "Malawi";
                    Country[Country["Malaysia"] = 103] = "Malaysia";
                    Country[Country["Maldives"] = 104] = "Maldives";
                    Country[Country["Mali"] = 105] = "Mali";
                    Country[Country["Malta"] = 106] = "Malta";
                    Country[Country["MarshallIslands"] = 107] = "MarshallIslands";
                    Country[Country["Mauritania"] = 108] = "Mauritania";
                    Country[Country["Mauritius"] = 109] = "Mauritius";
                    Country[Country["Mexico"] = 110] = "Mexico";
                    Country[Country["Micronesia"] = 111] = "Micronesia";
                    Country[Country["Moldova"] = 112] = "Moldova";
                    Country[Country["Monaco"] = 113] = "Monaco";
                    Country[Country["Mongolia"] = 114] = "Mongolia";
                    Country[Country["Montenegro"] = 115] = "Montenegro";
                    Country[Country["Morocco"] = 116] = "Morocco";
                    Country[Country["Mozambique"] = 117] = "Mozambique";
                    Country[Country["Myanmar"] = 118] = "Myanmar";
                    Country[Country["Namibia"] = 119] = "Namibia";
                    Country[Country["Nauru"] = 120] = "Nauru";
                    Country[Country["Nepal"] = 121] = "Nepal";
                    Country[Country["Netherlands"] = 122] = "Netherlands";
                    Country[Country["NewZealand"] = 123] = "NewZealand";
                    Country[Country["Nicaragua"] = 124] = "Nicaragua";
                    Country[Country["Niger"] = 125] = "Niger";
                    Country[Country["Nigeria"] = 126] = "Nigeria";
                    Country[Country["NorthKorea"] = 127] = "NorthKorea";
                    Country[Country["Norway"] = 128] = "Norway";
                    Country[Country["Oman"] = 129] = "Oman";
                    Country[Country["Pakistan"] = 130] = "Pakistan";
                    Country[Country["Palau"] = 131] = "Palau";
                    Country[Country["Palestine"] = 132] = "Palestine";
                    Country[Country["Panama"] = 133] = "Panama";
                    Country[Country["PapuaNewGuinea"] = 134] = "PapuaNewGuinea";
                    Country[Country["Paraguay"] = 135] = "Paraguay";
                    Country[Country["Peru"] = 136] = "Peru";
                    Country[Country["Philippines"] = 137] = "Philippines";
                    Country[Country["Poland"] = 138] = "Poland";
                    Country[Country["Portugal"] = 139] = "Portugal";
                    Country[Country["Qatar"] = 140] = "Qatar";
                    Country[Country["Romania"] = 141] = "Romania";
                    Country[Country["Russia"] = 142] = "Russia";
                    Country[Country["Rwanda"] = 143] = "Rwanda";
                    Country[Country["SaintKitts_Nevis"] = 144] = "SaintKitts_Nevis";
                    Country[Country["SaintLucia"] = 145] = "SaintLucia";
                    Country[Country["SaintVincent_theGrenadines"] = 146] = "SaintVincent_theGrenadines";
                    Country[Country["Samoa"] = 147] = "Samoa";
                    Country[Country["SanMarino"] = 148] = "SanMarino";
                    Country[Country["SaoTome_Principe"] = 149] = "SaoTome_Principe";
                    Country[Country["SaudiArabia"] = 150] = "SaudiArabia";
                    Country[Country["Senegal"] = 151] = "Senegal";
                    Country[Country["Serbia"] = 152] = "Serbia";
                    Country[Country["Seychelles"] = 153] = "Seychelles";
                    Country[Country["SierraLeone"] = 154] = "SierraLeone";
                    Country[Country["Singapore"] = 155] = "Singapore";
                    Country[Country["Slovakia"] = 156] = "Slovakia";
                    Country[Country["Slovenia"] = 157] = "Slovenia";
                    Country[Country["SolomonIslands"] = 158] = "SolomonIslands";
                    Country[Country["Somalia"] = 159] = "Somalia";
                    Country[Country["SouthAfrica"] = 160] = "SouthAfrica";
                    Country[Country["SouthKorea"] = 161] = "SouthKorea";
                    Country[Country["SouthSudan"] = 162] = "SouthSudan";
                    Country[Country["Spain"] = 163] = "Spain";
                    Country[Country["SriLanka"] = 164] = "SriLanka";
                    Country[Country["Sudan"] = 165] = "Sudan";
                    Country[Country["Suriname"] = 166] = "Suriname";
                    Country[Country["Swaziland"] = 167] = "Swaziland";
                    Country[Country["Sweden"] = 168] = "Sweden";
                    Country[Country["Switzerland"] = 169] = "Switzerland";
                    Country[Country["Syria"] = 170] = "Syria";
                    Country[Country["Taiwan"] = 171] = "Taiwan";
                    Country[Country["Tajikistan"] = 172] = "Tajikistan";
                    Country[Country["Tanzania"] = 173] = "Tanzania";
                    Country[Country["Thailand"] = 174] = "Thailand";
                    Country[Country["Timor_Leste"] = 175] = "Timor_Leste";
                    Country[Country["Togo"] = 176] = "Togo";
                    Country[Country["Tonga"] = 177] = "Tonga";
                    Country[Country["Trinidad_Tobago"] = 178] = "Trinidad_Tobago";
                    Country[Country["Tunisia"] = 179] = "Tunisia";
                    Country[Country["Turkey"] = 180] = "Turkey";
                    Country[Country["Turkmenistan"] = 181] = "Turkmenistan";
                    Country[Country["Tuvalu"] = 182] = "Tuvalu";
                    Country[Country["Uganda"] = 183] = "Uganda";
                    Country[Country["Ukraine"] = 184] = "Ukraine";
                    Country[Country["UnitedArabEmirates"] = 185] = "UnitedArabEmirates";
                    Country[Country["UnitedKingdom"] = 186] = "UnitedKingdom";
                    Country[Country["UnitedStatesofAmerica"] = 187] = "UnitedStatesofAmerica";
                    Country[Country["Uruguay"] = 188] = "Uruguay";
                    Country[Country["Uzbekistan"] = 189] = "Uzbekistan";
                    Country[Country["Vanuatu"] = 190] = "Vanuatu";
                    Country[Country["VaticanCity"] = 191] = "VaticanCity";
                    Country[Country["Venezuela"] = 192] = "Venezuela";
                    Country[Country["Vietnam"] = 193] = "Vietnam";
                    Country[Country["Yemen"] = 194] = "Yemen";
                    Country[Country["Zambia"] = 195] = "Zambia";
                    Country[Country["Zimbabwe"] = 196] = "Zimbabwe";
                })(Country = Auth.Country || (Auth.Country = {}));
                var SignupRequest = /** @class */ (function () {
                    function SignupRequest(username, email, password, unixBirthDate, nationality) {
                        this.Username = username;
                        this.Email = email;
                        this.Password = password;
                        this.UnixBirthDate = unixBirthDate;
                        this.Nationality = nationality;
                    }
                    return SignupRequest;
                }());
                Auth.SignupRequest = SignupRequest;
                var UserDto = /** @class */ (function () {
                    function UserDto(id, username, birthDate, nationality) {
                        this.Id = id;
                        this.Username = username;
                        this.BirthDate = birthDate;
                        this.Nationality = nationality;
                    }
                    return UserDto;
                }());
                Auth.UserDto = UserDto;
            })(Auth = Framework.Auth || (Framework.Auth = {}));
        })(Framework = TAW.Framework || (TAW.Framework = {}));
    })(TAW = UniVe.TAW || (UniVe.TAW = {}));
})(UniVe || (UniVe = {}));
//# sourceMappingURL=Auth.js.map